- name: "https://md.idem.garr.it/certs/idem-signer-20220121.pem"
  get_url: url="https://md.idem.garr.it/certs/idem-signer-20220121.pem" dest="{{ idp_path }}/metadata"

- name: "http://md.idem.garr.it/metadata/edugain2idem-metadata-sha256.xml"
  get_url: url="http://md.idem.garr.it/metadata/edugain2idem-metadata-sha256.xml" dest="{{ idp_path }}/metadata"  mode=777

- name: Add metadata-providers-eduGAIN.xml
  copy:
    src: roles/{{ role_name }}/files/metadata-providers-eduGAIN.xml
    dest:  "{{ idp_path }}/conf/metadata-providers-eduGAIN.xml"

- name: Add federation-cert
  copy:
    src: "roles/{{ role_name }}/files/federation-cert.pem"
    dest: "{{ idp_path }}/metadata/federation-cert.pem"

- name: "http://md.idem.garr.it/metadata/idem-test-metadata-sha256.xml"
  get_url: url="http://md.idem.garr.it/metadata/idem-test-metadata-sha256.xml" dest="{{ idp_path }}/metadata" mode=777

- name: Configure saml-nameid.properties (dataStore and persistentId)
  template:
    src: roles/{{ role_name }}/templates/saml-nameid.properties
    dest: "{{ idp_path }}/conf/saml-nameid.properties"
    backup: yes

#  add filters and md providers in services
- name: Add federation metadata provilders
  replace:
    path: "{{ idp_path }}/conf/services.xml"
    regexp: '<value>%{idp.home}/conf/metadata-providers.xml</value>'
    replace: '<value>%{idp.home}/conf/metadata-providers-eduGAIN.xml</value>\n
              \t<value>%{idp.home}/conf/metadata-providers.xml</value>'
    backup: yes

- name: "Add Attribute Filter: {{ idp_attr_filter }}"
  copy:
    src: roles/{{ role_name }}/files/{{ idp_attr_filter }}
    dest:  "{{ idp_path }}/conf/{{ idp_attr_filter }}"

# - name: "http://www.garr.it/idem-conf/attribute-filter-v3-required.xml"
  # get_url: url="https://raw.github.com/ConsortiumGARR/idem-tutorials/master/idem-fedops/HOWTO-Shibboleth/Identity%20Provider/utils/attribute-filter-v3-required.xml" dest="{{ idp_path }}/conf"

- name: "Attr registry: {{ idp_attr_reg_shac_url }}"
  get_url: url="{{ idp_attr_reg_shac_url }}" dest="{{ idp_path }}/conf/attributes/schac.xml"

- name: "Attr registry: {{ idp_attr_reg_ep_tid_url }}"
  get_url: url="{{ idp_attr_reg_ep_tid_url }}" dest="{{ idp_path }}/conf/attributes/custom/eduPersonTargetedID.properties"

- name: Add IDEM Attribute filters in services.xml (FileBackedHTTPResource bean)
  blockinfile:
    path: "{{ idp_path }}/conf/services.xml"
    insertbefore: '<util:list id ="shibboleth.AttributeFilterResources">'
    marker: "<!-- {mark} IDEM FileBackedHTTPResource attrfilters-->\n"
    block: |
        <bean id="IDEM-Production-Filter" class="net.shibboleth.ext.spring.resource.FileBackedHTTPResource"
           c:client-ref="shibboleth.FileCachingHttpClient"
           c:url="https://www.garr.it/idem-conf/attribute-filter-v3-required.xml"
           c:backingFile="%{idp.home}/conf/attribute-filter-v3-required.xml"/>
        <bean id="IDEM-Production-Filter-Anyone" class="net.shibboleth.ext.spring.resource.FileBackedHTTPResource"
           c:client-ref="shibboleth.FileCachingHttpClient"
           c:url="https://www.garr.it/idem-conf/attribute-filter.xml"
           c:backingFile="%{idp.home}/conf/attribute-filter-anyone.xml"/>
    # backup: yes

# - name: Add Attribute-filters in services.xml
  # blockinfile:
    # path: "{{ idp_path }}/conf/services.xml"
    # insertafter: '<value>%{idp.home}/conf/attribute-filter.xml</value>'
    # marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    # block: |8
            # <value>%{idp.home}/conf/attribute-filter-v3-RS-CoCo.xml</value>
            # <ref bean="IDEM-Production-Filter"/>
    # backup: yes

- name: Add Attribute-filters in services.xml
  replace:
    path: "{{ idp_path }}/conf/services.xml"
    regexp: '<value>%{idp.home}/conf/attribute-filter.xml</value>'
    replace: '<value>%{idp.home}/conf/attribute-filter.xml</value>\n
              \t<value>%{idp.home}/conf/{{ idp_attr_filter }}</value>\n
              \t<ref bean="IDEM-Production-Filter"/>\n
              \t<ref bean="IDEM-Production-Filter-Anyone"/>'
    backup: yes
